import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { ClerkProvider, ClerkLoaded } from '@clerk/nextjs';  // Import ClerkLoaded along with ClerkProvider

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Car Rent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
      <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the application with ClerkProvider */}
          {/* ClerkLoaded ensures Clerk is fully loaded before rendering */}
          <ClerkLoaded>
            <Navbar />
            {children}
            <Footer />
          </ClerkLoaded>
      </body>
    </html>
        </ClerkProvider>
  );
}
